### ISSUE TITLE
Error: cannot convert -1 to haddr_t

### ISSUE THREAD

**Issue by strombom** [Vindaar/nimhdf5#30]
I have installed nim 1.0 and nimhdf5 with nimble. 

After writing "import nimhdf5" I get an error "cannot convert -1 to haddr_t" on line 225 in H5public.nim which reads: "const HADDR_UNDEF* = (-1).clonglong.haddr_t".

**Comment by Vindaar** [comment]
Oh, I realize you might just be on an old `nimhdf5` version, since I haven't pushed a new version recently. Let me push a new release and please try again then.

**Comment by Vindaar** [comment]
Sorry, forgot about auto closing of GitHub.

Please try to update `nimhdf5` with nimble and see if the problem persists.

**Comment by strombom** [comment]
I can confirm that I get the error in version 0.2.14 but not in 0.2.15 and also not in 0.3.3.

**Comment by Vindaar** [comment]
That is great to hear! Then I'll close this issue. Feel free to open more. :)
