### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by telatin** [Vindaar/nimhdf5#42]
Hi there,
apologies for the naive question but I'm new to HDF5 libraries in general.

I'm using **Nim Version 1.2.6** and downloaded nimhdf5 **"0.3.13"** via nimble.

When trying to compile the suggested example:
```
nim c -r h5_high_level_example.nim 
```
I get compile time warnings and an error:
```

./examples/h5_high_level_example.nim(23, 13) Warning: Use `H5open` instead of H5file. The datatype was renamed from `H5FileObj` to `H5File`.; H5file is deprecated [Deprecated]
./examples/h5_high_level_example.nim(26, 19) template/generic instantiation of `create_dataset` from here
~/.nimble/pkgs/nimhdf5-0.3.13/nimhdf5/datasets.nim(568, 15) template/generic instantiation of `create_dataset` from here
~/.nimble/pkgs/nimhdf5-0.3.13/nimhdf5/datasets.nim(458, 31) template/generic instantiation of `getParentId` from here
~/.nimble/pkgs/nimhdf5-0.3.13/nimhdf5/h5util.nim(256, 21) template/generic instantiation of `getH5Id` from here
~/.nimble/pkgs/nimhdf5-0.3.13/nimhdf5/datatypes.nim(237, 15) Warning: Use `H5File` instead. This is a leftover naming scheme from when the H5 objects were not ref objects. This is an alias for H5File.; H5FileObj is deprecated [Deprecated]
~/.nimble/pkgs/nimhdf5-0.3.13/nimhdf5/h5util.nim(253, 5) Hint: 'parent' is declared but not used [XDeclaredButNotUsed]
/qi/nanopore/nimhdf5/examples/h5_high_level_example.nim(26, 19) template/generic instantiation of `create_dataset` from here
~/.nimble/pkgs/nimhdf5-0.3.13/nimhdf5/datasets.nim(568, 15) template/generic instantiation of `create_dataset` from here
~/.nimble/pkgs/nimhdf5-0.3.13/nimhdf5/datasets.nim(504, 26) template/generic instantiation of `delete` from here
~/.nimble/pkgs/nimhdf5-0.3.13/nimhdf5/h5util.nim(286, 21) template/generic instantiation of `getH5Id` from here
~/.nimble/pkgs/nimhdf5-0.3.13/nimhdf5/datatypes.nim(237, 15) Warning: Use `H5File` instead. This is a leftover naming scheme from when the H5 objects were not ref objects. This is an alias for H5File.; H5FileObj is deprecated [Deprecated]
/qi/nanopore/nimhdf5/examples/h5_high_level_example.nim(43, 12) Error: ambiguous call; both datatypes.name(t: typed) [declared in ~/.nimble/pkgs/nimhdf5-0.3.13/nimhdf5/datatypes.nim(257, 7)] and typetraits.name(t: typedesc) [declared in ~/.choosenim/toolchains/nim-1.2.6/lib/pure/typetraits.nim(19, 6)] match for: (type H5Group)
```

Do you have some guidance on how to get on track? Thanks

**Comment by Vindaar** [comment]
Hey!

first of all sorry for the state the documentation is in. It really needs some work, but as there hasn't been much interest in the library, it wasn't a priority so far.

The example you're running is seriously outdated I think. Most of the `nimhdf5` API hasn't changed too much, so the majority of the code should run fine I guess. It's just not part of the CI, which is a bit of a mistake.

The issue you're seeing I think is just that `name` doesn't exist anymore in `typetraits`. There's a few more regressions in that file. I'm pushing a fix to at least have the file compile and do something. 

For the time being it's best to look at the tests for how to use it (or ping me on discord / matrix and ask directly). I'll try to improve the docs situation sometime soonish.

**Comment by Vindaar** [comment]
See #43 for a version that compiles. Hope to push it in a few minutes (unless there's too much CI headache right now).

**Comment by telatin** [comment]
Thanks! Can't wait to give a try !

**Comment by Vindaar** [comment]
Great! Feel free to let me know about any annoying bits in particular.

**Comment by telatin** [comment]
Compiles perfectly  thanks :) I'll try to play with some h5 file now
