### ISSUE TITLE
`h5_create_dataset_hl` fails to compile

### ISSUE THREAD

**Issue by sdwfrost** [Vindaar/nimhdf5#6]
I get the following error on compiling the create dataset example, using Nim devel on OSX El Capitan:

```sh
$ nim c h5_create_dataset_hl
[snip]
.nimble/pkgs/nimhdf5-0.2.5/nimhdf5/datasets.nim(1121, 1) Error: undeclared identifier: 'g'
```

**Comment by Vindaar** [comment]
Sorry about that. I simply pushed a datasets.nim file containing a `g` somewhere in the code.

**Comment by sdwfrost** [comment]
Thanks! That fixes the compilation.
