### ISSUE TITLE
Change shared library suffix

### ISSUE THREAD

**Issue by sdwfrost** [Vindaar/nimhdf5#7]
The examples fail to run on e.g. OSX, though they should work in principle. The reference to the shared libraries should look something like this:

```
when defined(windows):
  const
    hdf5lib* = "hdf5.dll"
elif defined(macosx):
  const
    hdf5lib* = "libhdf5.dylib"
else:
  const
    hdf5lib* = "libhdf5.so"
```

**Comment by Vindaar** [comment]
Good point, thanks. I wasn't sure about the exact names of the shared library for Windows and OSX, which is why I left it out at first.

I'll fix it.

**Comment by sdwfrost** [comment]
Thanks! Works on OSX now.
