### ISSUE TITLE
String support for datasets.

### ISSUE THREAD

**Issue by ingoogni** [Vindaar/nimhdf5#74]
String support would be welcomed. Geo and climate data are full of string data and the ordering of things is not always the same. Without strings the other data is inaccessible.

```
{
  name: /station,
  opened: true,
  file: KMDS__OPER_P___10M_OBS_L2_202404020750.nc,
  parent: /,
  shape: @[56],
  dtype: string
}
@[1.114158639070125e-311, 1.114158639133366e-311, 1.114158638864594e-311, 1.114158639149176e-311,
 1.114158639204511e-311, 1.11415863891993e-311, 1.114158639157081e-311, 1.11415863901479e-311,
 1.114158638959455e-311, 1.114158638872499e-311, 1.114158639022695e-311, 1.114158639101746e-311,
 1.114158639109651e-311, 1.114158639164986e-311, 1.114158638927835e-311, 1.11415863896736e-311,
 1.114158639180796e-311.....
```

**Comment by ingoogni** [comment]
Sorry Vindaar, I just noticed I messed up. That's what one gets when one copies code. I created a seq for floats and gave it strings. It actually works fine with strings. Can be closed.

[KMDS__OPER_P___10M_OBS_L2_202404020750.zip](https://github.com/Vindaar/nimhdf5/files/14976956/KMDS__OPER_P___10M_OBS_L2_202404020750.zip)

**Comment by Vindaar** [comment]
Great to hear! Feel free to reopen / open another issue in case you need help!
